
    create table auto (
        cilindrata integer not null,
        id_auto integer generated by default as identity,
        numero_porte integer not null,
        veicolo_id integer unique,
        targa varchar(10) not null unique,
        primary key (id_auto)
    );

    create table bici (
        id_bici integer generated by default as identity,
        numero_marce integer not null,
        pieghevole boolean not null,
        veicolo_id integer unique,
        tipo_freno varchar(255) not null,
        tipo_sospensione varchar(255) not null,
        primary key (id_bici)
    );

    create table categoria (
        id_categoria integer generated by default as identity,
        descrizione varchar(100) not null unique,
        primary key (id_categoria)
    );

    create table colore (
        id_colore integer generated by default as identity,
        nome varchar(50) not null unique,
        primary key (id_colore)
    );

    create table messaggi_sistema (
        lang varchar(4) not null,
        code varchar(20) not null,
        messagio varchar(255),
        primary key (lang, code)
    );

    create table moto (
        cilindrata integer not null,
        id_moto integer generated by default as identity,
        veicolo_id integer unique,
        targa varchar(10) not null unique,
        primary key (id_moto)
    );

    create table tipo_alimentazione (
        id_tipo_alimentazione integer generated by default as identity,
        descrizione varchar(100) not null unique,
        primary key (id_tipo_alimentazione)
    );

    create table veicolo (
        anno_produzione integer not null,
        categoria_id integer,
        colore_id integer,
        id_veicoli integer generated by default as identity,
        numero_ruote integer not null,
        tipo_alimentazione_id integer,
        tipo_veicolo varchar(50) not null,
        marca varchar(100) not null,
        modello varchar(100) not null,
        primary key (id_veicoli)
    );

    alter table if exists auto 
       add constraint fk_auto_veicolo 
       foreign key (veicolo_id) 
       references veicolo;

    alter table if exists bici 
       add constraint fk_bici_veicolo 
       foreign key (veicolo_id) 
       references veicolo;

    alter table if exists moto 
       add constraint fk_moto_veicolo 
       foreign key (veicolo_id) 
       references veicolo;

    alter table if exists veicolo 
       add constraint FK1ffq24yvhb1147soqdmhcrr75 
       foreign key (categoria_id) 
       references categoria;

    alter table if exists veicolo 
       add constraint FKhawc18rfxiebdktlu7293kpom 
       foreign key (colore_id) 
       references colore;

    alter table if exists veicolo 
       add constraint FKmtqpek2bi3wm860ce0avhtqyp 
       foreign key (tipo_alimentazione_id) 
       references tipo_alimentazione;
