# =====================================================
# AUTO
# =====================================================

auto.selectByFilter=select a from Auto a \
left join a.veicolo v \
left join v.colore col \
left join v.categoria cat \
left join v.tipoAlimentazione alim \
where (:id is null or a.idAuto = :id) \
and (:targa is null or a.targa like :targa%) \
and (:marca is null or v.marca like :marca%) \
and (:modello is null or v.modello like :modello%) \
and (:colore is null or col.id = :colore) \
and (:categoria is null or cat.id = :categoria)

auto.getByTarga=select a from Auto a \
where a.targa = :targa

auto.getByTargaLikeA=select a from Auto a \
where a.targa like 'A%'



# =====================================================
# MOTO
# =====================================================

moto.selectByFilter=select m from Moto m \
left join m.veicolo v \
left join v.colore col \
left join v.categoria cat \
where (:id is null or m.idMoto = :id) \
and (:targa is null or m.targa like :targa%) \
and (:marca is null or v.marca like :marca%) \
and (:modello is null or v.modello like :modello%) \
and (:colore is null or col.id = :colore) \
and (:categoria is null or cat.id = :categoria)

moto.getByTarga=select m from Moto m \
where m.targa = :targa

moto.getByTargaLikeA=select m from Moto m \
where m.targa like 'A%'



# =====================================================
# BICI
# =====================================================

bici.selectByFilter=select b from Bici b \
left join b.veicolo v \
left join v.colore col \
left join v.categoria cat \
where (:id is null or b.idBici = :id) \
and (:marca is null or v.marca like :marca%) \
and (:modello is null or v.modello like :modello%) \
and (:colore is null or col.id = :colore) \
and (:categoria is null or cat.id = :categoria) \
and (:pieghevole is null or b.pieghevole = :pieghevole)

bici.getByMarcaLikeA=select b from Bici b \
join b.veicolo v \
where v.marca like 'A%'



# =====================================================
# VEICOLI
# =====================================================

veicoli.selectByFilter=select v from Veicoli v \
left join v.colore col \
left join v.categoria cat \
left join v.tipoAlimentazione alim \
where (:id is null or v.idVeicoli = :id) \
and (:tipoVeicolo is null or v.tipoVeicolo like :tipoVeicolo%) \
and (:marca is null or v.marca like :marca%) \
and (:modello is null or v.modello like :modello%) \
and (:colore is null or col.id = :colore) \
and (:categoria is null or cat.id = :categoria) \
and (:alimentazione is null or alim.id = :alimentazione)

veicoli.getByMarcaLikeA=select v from Veicoli v \
where v.marca like 'A%'